name: my Scheduled Python Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy bs4 requests lxml


      - name: Run Python script
        run: python test.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: test-csv
          path: test.csv  # Make sure this matches the filename in your script
