name: Morning Debrief

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 10:00 AM ET (14:00 UTC) every day

jobs:
  run-debrief:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run morning_debrief.py
        run: python morning_debrief.py
