name: Morning Debrief

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  update_metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CSV Generator Script
      run: python update_metadata.py

    - name: Commit and Push CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/player_metadata.csv
        git commit -m "Update player metadata"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

  morning_debrief:
    runs-on: ubuntu-latest
    needs: update_metadata

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script Using CSV
      env:
          GMAIL_APP_KEY: ${{ secrets.GMAIL_APP_KEY }}
      run: python morning_debrief.py

