name: Run Before NBA Games [19:00]

on:
  schedule:
  - cron: '5 22 7 4 *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Before Game Script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          START_TIME: 19
        run: python run_before_game.py --start-time $START_TIME

      - name: Commit and Push csv
        run: |
          git pull
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 'data/odds_first_basket.csv'
          git add 'data/rotowire_lineups.csv'
          git commit -m "Write new odds"
          git push https://x-access-token:${{ secrets.YML_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
