name: Run Script Before NBA Games

on:
  schedule:
    - cron: '30 18 27 11 *'
    - cron: '0 19 27 11 *'
    - cron: '30 19 27 11 *'
    - cron: '0 20 27 11 *'
    - cron: '30 20 27 11 *'
    - cron: '30 21 27 11 *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Before Game Script
        run: python run_before_game.py
